# Generated by Django 2.2.12 on 2022-04-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxuse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_table',
            old_name='name',
            new_name='username',
        ),
    ]
