# Generated by Django 2.2.12 on 2022-04-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxuse', '0002_auto_20220406_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_table',
            old_name='username',
            new_name='name',
        ),
    ]
