# Generated by Django 2.2.12 on 2022-04-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxuse', '0003_auto_20220406_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
